routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => ['web']], function () {
  Route::get('/', function () {
      return view('welcome');
  });

  Route::get('/example_form', function () {
      return view('example.form');
  });
	
	Auth::routes();

	Route::get('/home', 'HomeController@index');
	Route::resource('users', 'UserController');
	Route::resource('companies', 'CompanyController');
  Route::resource('plants', 'PlantController');
  Route::resource('technicians', 'TechnicianController');
});

app/Plant.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Plant extends Model
{
	use Notifiable;

    public function plant()
    {
        return $this->belongsTo('App\Plant');
    }

    public function empresa()
	{
		return $this->belongsToMany('App\User');
	} 
}

app/Http/Controllers/PlantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Plant;
use View;
use Session;


class PlantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $plants = Plant::all();

        // load the view and pass the users
        return View::make('plants.index')
            ->with('plants', $plants);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255|unique:companys',
            'email' => 'required|email|max:255|unique:companys',
            'address' => 'required|max:255',
            'ciudad' => 'required|max:255',
            'phone' => 'required|numeric|max:20',
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        /*return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'address' => $data['address'],
            'ciudad' => $data['ciudad'],
            'phone' => $data['phone'],
        ]);*/

        return view('plants.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        /*$this->validate($request, array(
            'name' => 'required|max:255|unique:companies',
            'email' => 'required|email|max:255|unique:companies',
            'address' => 'max:255',
            'city' => 'max:255',
            'phone' => 'numeric|max:20',
        ));*/

        $plant = new Plant;
        $plant->name = $request->name;
        $plant->summary = $request->summary;
        $plant->observations = $request->observations;
        $plant->image_plane = "imagen";
        $plant->company_id = $request->company_id;

        $plant->save();
        Session::flash('message', 'Planta guardada con éxito!');
        return redirect()->route('plants.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $plant = Plant::find($id);
        return view('plants.edit')->with('plant', $plant);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        /*$this->validate($request, array(
            'name' => 'required|max:255|unique:companies',
            'email' => 'required|email|max:255|unique:companies',
            'address' => 'max:255',
            'city' => 'max:255',
            'phone' => 'numeric|max:20',
        ));*/
        $plant = Plant::find($id);
        $plant->name = $request->name;
        $plant->summary = $request->summary;
        $plant->observations = $request->observations;
        //$plant->image_plane = $request->image_plane;
        $plant->company_id = $request->company_id;

      $plant->save();
      Session::flash('message', 'Planta guardado con éxito!');
      return redirect()->route('plants.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $plant = Plant::find($id);
        $plant->delete();
        return response()->json([
          'status' => 'ok'
      ]);
    }
}

resources/views/plants/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{!! route('plants.index'); !!}">Plantas</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Nueva Planta</span>
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn green btn-sm btn-outline"> Planta
                <i class="fa fa-angle-down"></i>
            </button>

        </div>
    </div>
</div>
<!-- END PAGE BAR -->

<div class="portlet light bordered">
  <div class="portlet-title">
      <div class="caption font-red-sunglo">
          <i class="icon-settings font-red-sunglo"></i>
          <span class="caption-subject bold uppercase"> Nueva Planta</span>
      </div>
  </div>
  <div class="portlet-body form">
      {!! Form::open(array('route' => 'plants.store')) !!}
          <div class="form-body">

            <div class="form-group">
              <label>Nombre</label>
              {{ Form::text('name', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Nombre')) }}
            </div>
            <div class="form-group">
              <label>Sumario</label>
              {{ Form::text('summary', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Sumario')) }}
            </div>
            <div class="form-group">
              <label>Observaciones</label>
              {{ Form::text('observations', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Observaciones')) }}
            </div>
            <div class="form-group">
              <label>Empresa</label>
              {{ Form::number('company_id', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Empresa')) }}
            </div>

          </div>
          <div class="form-actions">
              <button type="submit" class="btn blue">Guardar</button>
              <a href="{!! route('plants.index') !!}" class="btn default">Cancelar</a>
          </div>
      {!! Form::close() !!}
  </div>
</div>
@endsection

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/register') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>

                                @if ($errors->has('password_confirmation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/plants/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{!! route('plants.index'); !!}">Usuarios</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Editar usuario</span>
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn green btn-sm btn-outline"> Empresa
                <i class="fa fa-angle-down"></i>
            </button>

        </div>
    </div>
</div>
<!-- END PAGE BAR -->

<div class="portlet light bordered">
  <div class="portlet-title">
      <div class="caption font-red-sunglo">
          <i class="icon-settings font-red-sunglo"></i>
          <span class="caption-subject bold uppercase"> Nuevo Usuario</span>
      </div>
  </div>
  <div class="portlet-body form">
      {!! Form::model($plant, ['method' => 'PUT', 'route' => ['plants.update', $plant->id]]) !!}
          <div class="form-body">

            <div class="form-group">
              <label>Nombre</label>
              {{ Form::text('name', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Nombre')) }}
            </div>
            <div class="form-group">
              <label>Sumario</label>
              {{ Form::text('summary', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Sumario')) }}
            </div>
            <div class="form-group">
              <label>Observaciones</label>
              {{ Form::text('observations', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Observaciones')) }}
            </div>
            <div class="form-group">
              <label>Empresa</label>
              {{ Form::number('company_id', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Empresa')) }}
            </div>

          </div>
          <div class="form-actions">
              <button type="submit" class="btn blue">Guardar</button>
              <a href="{!! route('plants.index') !!}" class="btn default">Cancelar</a>
          </div>
      {!! Form::close() !!}
  </div>
</div>
@endsection

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/register') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>

                                @if ($errors->has('password_confirmation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/plants/index.blade.php
@extends('layouts.app')

@section('extra_js')
<script>
$( document ).ready(function() {
  $.ajaxSetup({ headers: { 'X-CSRF-TOKEN' : '{{ csrf_token() }}' } });
});
</script>
<script src="/js/user_index.js" type="text/javascript"></script>
@endsection

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Usuarios</span>
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn green btn-sm btn-outline"> Empresa
                <i class="fa fa-angle-down"></i>
            </button>

        </div>
    </div>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> Usuarios
    <small>Listado</small>
</h1>

<div class="portlet-body">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-12">
                <div class="btn-group pull-right">
                    <a id="sample_editable_1_new" class="btn sbold green" href="{!! route('plants.create'); !!}"> Agregar
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="main_table">
        <thead>
            <tr>
                <th> Planta </th>
                <th> Empresa</th>
                <th> Miembro desde </th>
                <th> Actions </th>
            </tr>
        </thead>
        <tbody>
          @foreach ($plants as $plant)
            <tr class="odd gradeX">

                <td> {{$plant->name}} </td>
                <td>
                   <!--aca va el nombre de la empresa-->
                </td>
                <td class="center"> {{$plant->created_at}} </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-xs green" href="{!! route('plants.edit', $plant->id) !!}" > Editar
                            <i class="fa fa-edit"></i>
                        </a>
                        <button class="btn btn-xs red bt_delete" type="button" data-url="{!! route('plants.destroy', $plant->id) !!}" > Eliminar
                            <i class="fa fa-remove"></i>
                        </button>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>


<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
@endsection