routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(['middleware' => ['web']], function () {
  Route::get('/', function () {
      return view('welcome');
  });

  Route::get('/example_form', function () {
      return view('example.form');
  });
	
	Auth::routes();

	Route::get('/home', 'HomeController@index');
	Route::resource('users', 'UserController');
	Route::resource('companies', 'CompanyController');
  Route::resource('plants', 'PlantController');
  Route::resource('technicians', 'TechnicianController');
});

app/Company.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
	use Notifiable;

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'city', 'address', 'phone',
    ];

    public function plants()
    {
       $this->hasMany('App\Plant');
    }

    public function users()
	{
		return $this->belongsToMany('App\User');
	} 
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Company;
use View;
use Session;


class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = Company::all();

        // load the view and pass the users
        return View::make('companies.index')
            ->with('companies', $companies);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255|unique:companys',
            'email' => 'required|email|max:255|unique:companys',
            'address' => 'required|max:255',
            'ciudad' => 'required|max:255',
            'phone' => 'required|numeric|max:20',
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        /*return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'address' => $data['address'],
            'ciudad' => $data['ciudad'],
            'phone' => $data['phone'],
        ]);*/

        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        /*$this->validate($request, array(
            'name' => 'required|max:255|unique:companies',
            'email' => 'required|email|max:255|unique:companies',
            'address' => 'max:255',
            'city' => 'max:255',
            'phone' => 'numeric|max:20',
        ));*/

        $company = new Company;
        $company->name = $request->name;
        $company->email = $request->email;
        $company->address = $request->address;
        $company->city = $request->city;
        $company->phone = $request->phone;

        $company->save();
        Session::flash('message', 'Empresa guardada con éxito!');
        return redirect()->route('companies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $company = Company::find($id);
        return view('companies.edit')->with('company', $company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        /*$this->validate($request, array(
            'name' => 'required|max:255|unique:companies',
            'email' => 'required|email|max:255|unique:companies',
            'address' => 'max:255',
            'city' => 'max:255',
            'phone' => 'numeric|max:20',
        ));*/
        $company = Company::find($id);
        $company->name = $request->name;
        $company->email = $request->email;
        $company->address = $request->address;
        $company->city = $request->city;
        $company->phone = $request->phone;

      $company->save();
      Session::flash('message', 'Empresa guardado con éxito!');
      return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $company = Company::find($id);
        $company->delete();
        return response()->json([
          'status' => 'ok'
      ]);
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{!! route('users.index'); !!}">Empresas</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Nueva empresa</span>
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn green btn-sm btn-outline"> Empresa
                <i class="fa fa-angle-down"></i>
            </button>
        </div>
    </div>
</div>
<!-- END PAGE BAR -->

<div class="portlet light bordered">
  <div class="portlet-title">
      <div class="caption font-red-sunglo">
          <i class="icon-settings font-red-sunglo"></i>
          <span class="caption-subject bold uppercase"> Nueva Empresa</span>
      </div>
  </div>
  <div class="portlet-body form">
      {!! Form::open(array('route' => 'companies.store')) !!}
          <div class="form-body">

            <div class="form-group">
                <label>Nombre</label>
                <div class="input-group">
                    <span class="input-group-addon input-circle-left">
                        <i class="fa fa-user"></i>
                    </span>
                    {{ Form::text('name', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Empresa')) }}

            </div>

              <div class="form-group">
                  <label>Email Address</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <i class="fa fa-envelope"></i>
                      </span>
                      {{ Form::text('email', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Email')) }}
              </div>

              <div class="form-group">
                  <label>Ciudad</label>
                  {{ Form::text('city', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Ciudad')) }}
              </div>

              <div class="form-group">
                  <label>Direccion</label>
                  {{ Form::text('address', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Direccion')) }}
              </div>

              <div class="form-group">
                  <label>Telefono</label>
                  {{ Form::number('phone', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Telefono')) }}
              </div>

          </div>
          <div class="form-actions">
              <button type="submit" class="btn blue">Guardar</button>
              <a href="{!! route('companies.index') !!}" class="btn default">Cancelar</a>
          </div>
      {!! Form::close() !!}
  </div>
</div>
@endsection

@section('content2')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/register') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>

                                @if ($errors->has('password_confirmation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-bar">
  <ul class="page-breadcrumb">
    <li>
      <a href="/">Home</a>
      <i class="fa fa-circle"></i>
    </li>
    <li>
      <a href="{!! route('companies.index'); !!}">Empresas</a>
      <i class="fa fa-circle"></i>
    </li>
    <li>
      <span>Editar empresa</span>
    </li>
  </ul>
  <div class="page-toolbar">
    <div class="btn-group pull-right">
      <button type="button" class="btn green btn-sm btn-outline"> Empresa
        <i class="fa fa-angle-down"></i>
      </button>

    </div>
  </div>
</div>
<!-- END PAGE BAR -->

<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-red-sunglo">
      <i class="icon-settings font-red-sunglo">
      </i>
      <span class="caption-subject bold uppercase">
        Editar Empresa
      </span>
    </div>
  </div>
  <div class="portlet-body form">
    {!! Form::model($company, ['method' => 'PUT', 'route' => ['companies.update', $company->id]]) !!}
    <div class="form-body">

      <div class="form-group">
        <label>Nombre</label>
        <div class="input-group">
          <span class="input-group-addon input-circle-left">
            <i class="fa fa-user"></i>
          </span>
          {{ Form::text('name', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Empresa')) }}

        </div>

        <div class="form-group">
          <label>Email Address</label>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-envelope"></i>
            </span>
            {{ Form::text('email', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Email')) }}
          </div>

          <div class="form-group">
            <label>Ciudad</label>
            {{ Form::text('city', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Ciudad')) }}
          </div>

          <div class="form-group">
            <label>Direccion</label>
            {{ Form::text('address', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Direccion')) }}
          </div>

          <div class="form-group">
            <label>Telefono</label>
            {{ Form::number('phone', null, array('class' => 'form-control input-circle-right', 'placeholder' => 'Telefono')) }}
          </div>

        </div>
        <div class="form-actions">
          <button type="submit" class="btn blue">Guardar</button>
          <a href="{!! route('companies.index') !!}" class="btn default">Cancelar</a>
        </div>
        {!! Form::close() !!}
      </div>
    </div>
    @endsection

    @section('content2')
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">Register</div>
            <div class="panel-body">
              <form class="form-horizontal" role="form" method="POST" action="{{ url('/register') }}">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                  <label for="name" class="col-md-4 control-label">Name</label>

                  <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                    <span class="help-block">
                      <strong>{{ $errors->first('name') }}</strong>
                    </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                  <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                  <div class="col-md-6">
                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                    @if ($errors->has('email'))
                    <span class="help-block">
                      <strong>{{ $errors->first('email') }}</strong>
                    </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                  <label for="password" class="col-md-4 control-label">Password</label>

                  <div class="col-md-6">
                    <input id="password" type="password" class="form-control" name="password" required>

                    @if ($errors->has('password'))
                    <span class="help-block">
                      <strong>{{ $errors->first('password') }}</strong>
                    </span>
                    @endif
                  </div>
                </div>

                <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                  <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                  <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>

                    @if ($errors->has('password_confirmation'))
                    <span class="help-block">
                      <strong>{{ $errors->first('password_confirmation') }}</strong>
                    </span>
                    @endif
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                      Register
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    @endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('extra_js')
<script>
$( document ).ready(function() {
  $.ajaxSetup({ headers: { 'X-CSRF-TOKEN' : '{{ csrf_token() }}' } });
});
</script>
<script src="/js/user_index.js" type="text/javascript"></script>
@endsection

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Empresas</span>
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn green btn-sm btn-outline"> Empresa
                <i class="fa fa-angle-down"></i>
            </button>

        </div>
    </div>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> Empresas
    <small>Listado</small>
</h1>

<div class="portlet-body">
    <div class="table-toolbar">
        <div class="row">
            <div class="col-md-12">
                <div class="btn-group pull-right">
                    <a id="sample_editable_1_new" class="btn sbold green" href="{!! route('companies.create'); !!}"> Agregar
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="main_table">
        <thead>
            <tr>
                <th> Empresa </th>
                <th> Email </th>
                <th> Fecha de creacion </th>
                <th> Actions </th>
            </tr>
        </thead>
        <tbody>
          @foreach ($companies as $company)
            <tr class="odd gradeX">

                <td> {{$company->name}} </td>
                <td>
                    <a href="mailto:{{$company->email}}"> {{$company->email}} </a>
                </td>
                <td class="center"> {{$company->created_at}} </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-xs green" href="{!! route('companies.edit', $company->id) !!}" > Editar
                            <i class="fa fa-edit"></i>
                        </a>
                        <button class="btn btn-xs red bt_delete" type="button" data-url="{!! route('companies.destroy', $company->id) !!}" > Eliminar
                            <i class="fa fa-remove"></i>
                        </button>
                    </div>
                </td>
            </tr>
          @endforeach
        </tbody>
    </table>
</div>


<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
@endsection